"""empty message

Revision ID: 3307ef2feebd
Revises: 6faf96a4e07d
Create Date: 2024-03-28 20:21:47.523356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3307ef2feebd'
down_revision = '6faf96a4e07d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatars_equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipped', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatars_equipment', schema=None) as batch_op:
        batch_op.drop_column('equipped')

    # ### end Alembic commands ###
